services:
  client:
    build: ./client
    ports:
      - "5173:5173"  
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server

  server:
    build: ./server
    ports:
      - "5001:5001"